library(ggfortify)
ggdistribution(dnorm, mtcars$mpg, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$cyl, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$hp, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$drat, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$wt, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$qsec, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$vs, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$am, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$gear, mean = 0, sd = 1)
ggdistribution(dnorm, mtcars$carb, mean = 0, sd = 1)